input {
  stdin {
    codec => line
  }
}

filter {
  if [message] =~ / endpoint: / {
    grok {
      match => {
        "message" => "^%{TIMESTAMP_ISO8601:syslog_ts} %{HOSTNAME:node} endpoint: \[%{TIMESTAMP_ISO8601:time}\] %{NOTSPACE:remote_addr} %{INT:status:int} %{INT:bytes_sent:int} %{INT:request_length:int} %{NUMBER:request_time:float} \"%{DATA:endpoint_id}\" \"%{DATA:upstream_addr}\" \"%{DATA:request}\" \"%{DATA:http_host}\"$"
      }
      tag_on_failure => ["_storagegrid_endpoint_grok_failure"]
    }
    mutate {
      add_field => { "log_type" => "endpoint" }
    }
  } else if [message] =~ / mgmt: / {
    grok {
      match => {
        "message" => "^%{TIMESTAMP_ISO8601:syslog_ts} %{HOSTNAME:node} mgmt: \[%{TIMESTAMP_ISO8601:time}\] %{NOTSPACE:remote_addr} %{INT:status:int} %{INT:bytes_sent:int} %{INT:request_length:int} %{NUMBER:request_time:float} \"%{DATA:session_id}\" \"%{DATA:request}\" \"%{DATA:http_host}\" \"%{DATA:user_agent}\" \"%{DATA:http_referer}\"$"
      }
      tag_on_failure => ["_storagegrid_mgmt_grok_failure"]
    }
    mutate {
      add_field => { "log_type" => "mgmt" }
    }
  } else {
    drop { }
  }
}

output {
  stdout {
    codec => json_lines
  }
}
